
package logica.servidor;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "ExceptionCostoPaqueteNoNegativo", targetNamespace = "http://servidor.logica/")
public class ExceptionCostoPaqueteNoNegativo_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ExceptionCostoPaqueteNoNegativo faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ExceptionCostoPaqueteNoNegativo_Exception(String message, ExceptionCostoPaqueteNoNegativo faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public ExceptionCostoPaqueteNoNegativo_Exception(String message, ExceptionCostoPaqueteNoNegativo faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: logica.servidor.ExceptionCostoPaqueteNoNegativo
     */
    public ExceptionCostoPaqueteNoNegativo getFaultInfo() {
        return faultInfo;
    }

}
