
package logica.servidor;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "ExceptionDescuentoInvalido", targetNamespace = "http://servidor.logica/")
public class ExceptionDescuentoInvalido_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ExceptionDescuentoInvalido faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ExceptionDescuentoInvalido_Exception(String message, ExceptionDescuentoInvalido faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public ExceptionDescuentoInvalido_Exception(String message, ExceptionDescuentoInvalido faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: logica.servidor.ExceptionDescuentoInvalido
     */
    public ExceptionDescuentoInvalido getFaultInfo() {
        return faultInfo;
    }

}
