
package logica.servidor;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "Servidor", targetNamespace = "http://servidor.logica/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Servidor {


    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @throws ExceptionCantidadRestanteDeUnTipoDeOfertaEnUnPaqueteEsNegativa_Exception
     * @throws ExceptionCompraPaqueteConValorNegativo_Exception
     * @throws ExceptionUsuarioNoEncontrado_Exception
     * @throws ExceptionValidezNegativa_Exception
     * @throws NoExistePaquete_Exception
     */
    @WebMethod
    @Action(input = "http://servidor.logica/Servidor/compraPaquetesRequest", output = "http://servidor.logica/Servidor/compraPaquetesResponse", fault = {
        @FaultAction(className = ExceptionCompraPaqueteConValorNegativo_Exception.class, value = "http://servidor.logica/Servidor/compraPaquetes/Fault/ExceptionCompraPaqueteConValorNegativo"),
        @FaultAction(className = ExceptionCantidadRestanteDeUnTipoDeOfertaEnUnPaqueteEsNegativa_Exception.class, value = "http://servidor.logica/Servidor/compraPaquetes/Fault/ExceptionCantidadRestanteDeUnTipoDeOfertaEnUnPaqueteEsNegativa"),
        @FaultAction(className = ExceptionValidezNegativa_Exception.class, value = "http://servidor.logica/Servidor/compraPaquetes/Fault/ExceptionValidezNegativa"),
        @FaultAction(className = ExceptionUsuarioNoEncontrado_Exception.class, value = "http://servidor.logica/Servidor/compraPaquetes/Fault/ExceptionUsuarioNoEncontrado"),
        @FaultAction(className = NoExistePaquete_Exception.class, value = "http://servidor.logica/Servidor/compraPaquetes/Fault/NoExistePaquete")
    })
    public void compraPaquetes(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        int arg3)
        throws ExceptionCantidadRestanteDeUnTipoDeOfertaEnUnPaqueteEsNegativa_Exception, ExceptionCompraPaqueteConValorNegativo_Exception, ExceptionUsuarioNoEncontrado_Exception, ExceptionValidezNegativa_Exception, NoExistePaquete_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns logica.servidor.DtOfertaExtendidoSinPConK
     * @throws OfertaLaboralNoEncontrada_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.logica/Servidor/infoOfertaLaboralPostulanteRequest", output = "http://servidor.logica/Servidor/infoOfertaLaboralPostulanteResponse", fault = {
        @FaultAction(className = OfertaLaboralNoEncontrada_Exception.class, value = "http://servidor.logica/Servidor/infoOfertaLaboralPostulante/Fault/OfertaLaboralNoEncontrada")
    })
    public DtOfertaExtendidoSinPConK infoOfertaLaboralPostulante(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws OfertaLaboralNoEncontrada_Exception
    ;

    /**
     * 
     * @param apellido
     * @param correo
     * @param description
     * @param nickname
     * @param nombre
     * @param password
     * @param url
     * @throws ErrorAgregarUsuario_Exception
     * @throws ExceptionUsuarioCorreoRepetido_Exception
     * @throws ExceptionUsuarioNickRepetido_Exception
     * @throws ExceptionUsuarioNickYCorreoRepetidos_Exception
     */
    @WebMethod
    @Action(input = "http://servidor.logica/Servidor/altaEmpresaURLRequest", output = "http://servidor.logica/Servidor/altaEmpresaURLResponse", fault = {
        @FaultAction(className = ExceptionUsuarioCorreoRepetido_Exception.class, value = "http://servidor.logica/Servidor/altaEmpresaURL/Fault/ExceptionUsuarioCorreoRepetido"),
        @FaultAction(className = ExceptionUsuarioNickYCorreoRepetidos_Exception.class, value = "http://servidor.logica/Servidor/altaEmpresaURL/Fault/ExceptionUsuarioNickYCorreoRepetidos"),
        @FaultAction(className = ExceptionUsuarioNickRepetido_Exception.class, value = "http://servidor.logica/Servidor/altaEmpresaURL/Fault/ExceptionUsuarioNickRepetido"),
        @FaultAction(className = ErrorAgregarUsuario_Exception.class, value = "http://servidor.logica/Servidor/altaEmpresaURL/Fault/ErrorAgregarUsuario")
    })
    public void altaEmpresaURL(
        @WebParam(name = "nickname", partName = "nickname")
        String nickname,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "nombre", partName = "nombre")
        String nombre,
        @WebParam(name = "apellido", partName = "apellido")
        String apellido,
        @WebParam(name = "correo", partName = "correo")
        String correo,
        @WebParam(name = "description", partName = "description")
        String description,
        @WebParam(name = "url", partName = "url")
        String url)
        throws ErrorAgregarUsuario_Exception, ExceptionUsuarioCorreoRepetido_Exception, ExceptionUsuarioNickRepetido_Exception, ExceptionUsuarioNickYCorreoRepetidos_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @return
     *     returns boolean
     * @throws ErrorAgregarUsuario_Exception
     * @throws ExceptionFechaInvalida_Exception
     * @throws ExceptionUsuarioCorreoRepetido_Exception
     * @throws ExceptionUsuarioNickRepetido_Exception
     * @throws ExceptionUsuarioNickYCorreoRepetidos_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.logica/Servidor/altaPostulanteRequest", output = "http://servidor.logica/Servidor/altaPostulanteResponse", fault = {
        @FaultAction(className = ExceptionUsuarioCorreoRepetido_Exception.class, value = "http://servidor.logica/Servidor/altaPostulante/Fault/ExceptionUsuarioCorreoRepetido"),
        @FaultAction(className = ExceptionUsuarioNickYCorreoRepetidos_Exception.class, value = "http://servidor.logica/Servidor/altaPostulante/Fault/ExceptionUsuarioNickYCorreoRepetidos"),
        @FaultAction(className = ExceptionUsuarioNickRepetido_Exception.class, value = "http://servidor.logica/Servidor/altaPostulante/Fault/ExceptionUsuarioNickRepetido"),
        @FaultAction(className = ExceptionFechaInvalida_Exception.class, value = "http://servidor.logica/Servidor/altaPostulante/Fault/ExceptionFechaInvalida"),
        @FaultAction(className = ErrorAgregarUsuario_Exception.class, value = "http://servidor.logica/Servidor/altaPostulante/Fault/ErrorAgregarUsuario")
    })
    public boolean altaPostulante(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5,
        @WebParam(name = "arg6", partName = "arg6")
        String arg6)
        throws ErrorAgregarUsuario_Exception, ExceptionFechaInvalida_Exception, ExceptionUsuarioCorreoRepetido_Exception, ExceptionUsuarioNickRepetido_Exception, ExceptionUsuarioNickYCorreoRepetidos_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns logica.servidor.DtUsuario
     * @throws ExceptionUsuarioNoEncontrado_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.logica/Servidor/obtenerDatosUsuarioRequest", output = "http://servidor.logica/Servidor/obtenerDatosUsuarioResponse", fault = {
        @FaultAction(className = ExceptionUsuarioNoEncontrado_Exception.class, value = "http://servidor.logica/Servidor/obtenerDatosUsuario/Fault/ExceptionUsuarioNoEncontrado")
    })
    public DtUsuario obtenerDatosUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws ExceptionUsuarioNoEncontrado_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg10
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @param arg7
     * @param arg8
     * @param arg9
     * @throws ExceptionCantidadRestanteDeUnTipoDeOfertaEnUnPaqueteEsNegativa_Exception
     * @throws ExceptionCostoPaqueteNoNegativo_Exception
     * @throws ExceptionDescuentoInvalido_Exception
     * @throws ExceptionPaqueteNoVigente_Exception
     * @throws ExceptionRemuneracionOfertaLaboralNegativa_Exception
     * @throws ExceptionUsuarioNoEncontrado_Exception
     * @throws NoExistePaquete_Exception
     */
    @WebMethod
    @Action(input = "http://servidor.logica/Servidor/altaOfertaLaboralRequest", output = "http://servidor.logica/Servidor/altaOfertaLaboralResponse", fault = {
        @FaultAction(className = ExceptionRemuneracionOfertaLaboralNegativa_Exception.class, value = "http://servidor.logica/Servidor/altaOfertaLaboral/Fault/ExceptionRemuneracionOfertaLaboralNegativa"),
        @FaultAction(className = ExceptionUsuarioNoEncontrado_Exception.class, value = "http://servidor.logica/Servidor/altaOfertaLaboral/Fault/ExceptionUsuarioNoEncontrado"),
        @FaultAction(className = NoExistePaquete_Exception.class, value = "http://servidor.logica/Servidor/altaOfertaLaboral/Fault/NoExistePaquete"),
        @FaultAction(className = ExceptionCostoPaqueteNoNegativo_Exception.class, value = "http://servidor.logica/Servidor/altaOfertaLaboral/Fault/ExceptionCostoPaqueteNoNegativo"),
        @FaultAction(className = ExceptionPaqueteNoVigente_Exception.class, value = "http://servidor.logica/Servidor/altaOfertaLaboral/Fault/ExceptionPaqueteNoVigente"),
        @FaultAction(className = ExceptionCantidadRestanteDeUnTipoDeOfertaEnUnPaqueteEsNegativa_Exception.class, value = "http://servidor.logica/Servidor/altaOfertaLaboral/Fault/ExceptionCantidadRestanteDeUnTipoDeOfertaEnUnPaqueteEsNegativa"),
        @FaultAction(className = ExceptionDescuentoInvalido_Exception.class, value = "http://servidor.logica/Servidor/altaOfertaLaboral/Fault/ExceptionDescuentoInvalido")
    })
    public void altaOfertaLaboral(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5,
        @WebParam(name = "arg6", partName = "arg6")
        float arg6,
        @WebParam(name = "arg7", partName = "arg7")
        String arg7,
        @WebParam(name = "arg8", partName = "arg8")
        String arg8,
        @WebParam(name = "arg9", partName = "arg9")
        String arg9,
        @WebParam(name = "arg10", partName = "arg10")
        String arg10)
        throws ExceptionCantidadRestanteDeUnTipoDeOfertaEnUnPaqueteEsNegativa_Exception, ExceptionCostoPaqueteNoNegativo_Exception, ExceptionDescuentoInvalido_Exception, ExceptionPaqueteNoVigente_Exception, ExceptionRemuneracionOfertaLaboralNegativa_Exception, ExceptionUsuarioNoEncontrado_Exception, NoExistePaquete_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns logica.servidor.DtOfertaExtendidoSinPConK
     * @throws OfertaLaboralNoEncontrada_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.logica/Servidor/infoOfertaLaboralVisitanteRequest", output = "http://servidor.logica/Servidor/infoOfertaLaboralVisitanteResponse", fault = {
        @FaultAction(className = OfertaLaboralNoEncontrada_Exception.class, value = "http://servidor.logica/Servidor/infoOfertaLaboralVisitante/Fault/OfertaLaboralNoEncontrada")
    })
    public DtOfertaExtendidoSinPConK infoOfertaLaboralVisitante(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws OfertaLaboralNoEncontrada_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns logica.servidor.DtPostulacion
     * @throws ExceptionUsuarioNoEncontrado_Exception
     * @throws TipoUsuarioNoValido_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.logica/Servidor/obtenerDatosPostulacionWRequest", output = "http://servidor.logica/Servidor/obtenerDatosPostulacionWResponse", fault = {
        @FaultAction(className = ExceptionUsuarioNoEncontrado_Exception.class, value = "http://servidor.logica/Servidor/obtenerDatosPostulacionW/Fault/ExceptionUsuarioNoEncontrado"),
        @FaultAction(className = TipoUsuarioNoValido_Exception.class, value = "http://servidor.logica/Servidor/obtenerDatosPostulacionW/Fault/TipoUsuarioNoValido")
    })
    public DtPostulacion obtenerDatosPostulacionW(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws ExceptionUsuarioNoEncontrado_Exception, TipoUsuarioNoValido_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns logica.servidor.DtPaquete
     * @throws NoExistePaquete_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.logica/Servidor/obtenerDatosPaqueteRequest", output = "http://servidor.logica/Servidor/obtenerDatosPaqueteResponse", fault = {
        @FaultAction(className = NoExistePaquete_Exception.class, value = "http://servidor.logica/Servidor/obtenerDatosPaquete/Fault/NoExistePaquete")
    })
    public DtPaquete obtenerDatosPaquete(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws NoExistePaquete_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns boolean
     * @throws ExceptionUsuarioNoEncontrado_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.logica/Servidor/validarCredencialesRequest", output = "http://servidor.logica/Servidor/validarCredencialesResponse", fault = {
        @FaultAction(className = ExceptionUsuarioNoEncontrado_Exception.class, value = "http://servidor.logica/Servidor/validarCredenciales/Fault/ExceptionUsuarioNoEncontrado")
    })
    public boolean validarCredenciales(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws ExceptionUsuarioNoEncontrado_Exception
    ;

    /**
     * 
     * @param apellido
     * @param correo
     * @param fechaNacimientoString
     * @param imagen
     * @param nacionalidad
     * @param nickname
     * @param nombre
     * @param password
     * @throws ExceptionUsuarioNoEncontrado_Exception
     */
    @WebMethod
    @Action(input = "http://servidor.logica/Servidor/ingresarDatosEditadosPostulanteImgRequest", output = "http://servidor.logica/Servidor/ingresarDatosEditadosPostulanteImgResponse", fault = {
        @FaultAction(className = ExceptionUsuarioNoEncontrado_Exception.class, value = "http://servidor.logica/Servidor/ingresarDatosEditadosPostulanteImg/Fault/ExceptionUsuarioNoEncontrado")
    })
    public void ingresarDatosEditadosPostulanteImg(
        @WebParam(name = "nickname", partName = "nickname")
        String nickname,
        @WebParam(name = "nombre", partName = "nombre")
        String nombre,
        @WebParam(name = "apellido", partName = "apellido")
        String apellido,
        @WebParam(name = "correo", partName = "correo")
        String correo,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "imagen", partName = "imagen")
        byte[] imagen,
        @WebParam(name = "fechaNacimientoString", partName = "fechaNacimientoString")
        String fechaNacimientoString,
        @WebParam(name = "nacionalidad", partName = "nacionalidad")
        String nacionalidad)
        throws ExceptionUsuarioNoEncontrado_Exception
    ;

    /**
     * 
     * @param apellido
     * @param correo
     * @param fechaNacimientoString
     * @param nacionalidad
     * @param nickname
     * @param nombre
     * @param password
     * @throws ExceptionUsuarioNoEncontrado_Exception
     */
    @WebMethod
    @Action(input = "http://servidor.logica/Servidor/ingresarDatosEditadosPostulanteRequest", output = "http://servidor.logica/Servidor/ingresarDatosEditadosPostulanteResponse", fault = {
        @FaultAction(className = ExceptionUsuarioNoEncontrado_Exception.class, value = "http://servidor.logica/Servidor/ingresarDatosEditadosPostulante/Fault/ExceptionUsuarioNoEncontrado")
    })
    public void ingresarDatosEditadosPostulante(
        @WebParam(name = "nickname", partName = "nickname")
        String nickname,
        @WebParam(name = "nombre", partName = "nombre")
        String nombre,
        @WebParam(name = "apellido", partName = "apellido")
        String apellido,
        @WebParam(name = "correo", partName = "correo")
        String correo,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "fechaNacimientoString", partName = "fechaNacimientoString")
        String fechaNacimientoString,
        @WebParam(name = "nacionalidad", partName = "nacionalidad")
        String nacionalidad)
        throws ExceptionUsuarioNoEncontrado_Exception
    ;

    /**
     * 
     * @param apellido
     * @param correo
     * @param descripcion
     * @param nickname
     * @param nombre
     * @param password
     * @param url
     * @throws ExceptionUsuarioNoEncontrado_Exception
     */
    @WebMethod
    @Action(input = "http://servidor.logica/Servidor/ingresarDatosEditadosEmpresaURLRequest", output = "http://servidor.logica/Servidor/ingresarDatosEditadosEmpresaURLResponse", fault = {
        @FaultAction(className = ExceptionUsuarioNoEncontrado_Exception.class, value = "http://servidor.logica/Servidor/ingresarDatosEditadosEmpresaURL/Fault/ExceptionUsuarioNoEncontrado")
    })
    public void ingresarDatosEditadosEmpresaURL(
        @WebParam(name = "nickname", partName = "nickname")
        String nickname,
        @WebParam(name = "nombre", partName = "nombre")
        String nombre,
        @WebParam(name = "apellido", partName = "apellido")
        String apellido,
        @WebParam(name = "correo", partName = "correo")
        String correo,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "URL", partName = "URL")
        String url,
        @WebParam(name = "descripcion", partName = "descripcion")
        String descripcion)
        throws ExceptionUsuarioNoEncontrado_Exception
    ;

    /**
     * 
     * @param apellido
     * @param correo
     * @param descripcion
     * @param nickname
     * @param nombre
     * @param password
     * @throws ExceptionUsuarioNoEncontrado_Exception
     */
    @WebMethod
    @Action(input = "http://servidor.logica/Servidor/ingresarDatosEditadosEmpresaRequest", output = "http://servidor.logica/Servidor/ingresarDatosEditadosEmpresaResponse", fault = {
        @FaultAction(className = ExceptionUsuarioNoEncontrado_Exception.class, value = "http://servidor.logica/Servidor/ingresarDatosEditadosEmpresa/Fault/ExceptionUsuarioNoEncontrado")
    })
    public void ingresarDatosEditadosEmpresa(
        @WebParam(name = "nickname", partName = "nickname")
        String nickname,
        @WebParam(name = "nombre", partName = "nombre")
        String nombre,
        @WebParam(name = "apellido", partName = "apellido")
        String apellido,
        @WebParam(name = "correo", partName = "correo")
        String correo,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "descripcion", partName = "descripcion")
        String descripcion)
        throws ExceptionUsuarioNoEncontrado_Exception
    ;

    /**
     * 
     * @param apellido
     * @param correo
     * @param descripcion
     * @param imagen
     * @param nickname
     * @param nombre
     * @param password
     * @param url
     * @throws ExceptionUsuarioNoEncontrado_Exception
     */
    @WebMethod
    @Action(input = "http://servidor.logica/Servidor/ingresarDatosEditadosEmpresaURLImgRequest", output = "http://servidor.logica/Servidor/ingresarDatosEditadosEmpresaURLImgResponse", fault = {
        @FaultAction(className = ExceptionUsuarioNoEncontrado_Exception.class, value = "http://servidor.logica/Servidor/ingresarDatosEditadosEmpresaURLImg/Fault/ExceptionUsuarioNoEncontrado")
    })
    public void ingresarDatosEditadosEmpresaURLImg(
        @WebParam(name = "nickname", partName = "nickname")
        String nickname,
        @WebParam(name = "nombre", partName = "nombre")
        String nombre,
        @WebParam(name = "apellido", partName = "apellido")
        String apellido,
        @WebParam(name = "correo", partName = "correo")
        String correo,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "URL", partName = "URL")
        String url,
        @WebParam(name = "imagen", partName = "imagen")
        byte[] imagen,
        @WebParam(name = "descripcion", partName = "descripcion")
        String descripcion)
        throws ExceptionUsuarioNoEncontrado_Exception
    ;

    /**
     * 
     * @param apellido
     * @param correo
     * @param descripcion
     * @param imagen
     * @param nickname
     * @param nombre
     * @param password
     * @throws ExceptionUsuarioNoEncontrado_Exception
     */
    @WebMethod
    @Action(input = "http://servidor.logica/Servidor/ingresarDatosEditadosEmpresaImgRequest", output = "http://servidor.logica/Servidor/ingresarDatosEditadosEmpresaImgResponse", fault = {
        @FaultAction(className = ExceptionUsuarioNoEncontrado_Exception.class, value = "http://servidor.logica/Servidor/ingresarDatosEditadosEmpresaImg/Fault/ExceptionUsuarioNoEncontrado")
    })
    public void ingresarDatosEditadosEmpresaImg(
        @WebParam(name = "nickname", partName = "nickname")
        String nickname,
        @WebParam(name = "nombre", partName = "nombre")
        String nombre,
        @WebParam(name = "apellido", partName = "apellido")
        String apellido,
        @WebParam(name = "correo", partName = "correo")
        String correo,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "imagen", partName = "imagen")
        byte[] imagen,
        @WebParam(name = "descripcion", partName = "descripcion")
        String descripcion)
        throws ExceptionUsuarioNoEncontrado_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     * @throws ExceptionUsuarioNoEncontrado_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.logica/Servidor/tieneURLRequest", output = "http://servidor.logica/Servidor/tieneURLResponse", fault = {
        @FaultAction(className = ExceptionUsuarioNoEncontrado_Exception.class, value = "http://servidor.logica/Servidor/tieneURL/Fault/ExceptionUsuarioNoEncontrado")
    })
    public boolean tieneURL(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws ExceptionUsuarioNoEncontrado_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns boolean
     * @throws ExceptionUsuarioNoEncontrado_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.logica/Servidor/hayPostulacionWRequest", output = "http://servidor.logica/Servidor/hayPostulacionWResponse", fault = {
        @FaultAction(className = ExceptionUsuarioNoEncontrado_Exception.class, value = "http://servidor.logica/Servidor/hayPostulacionW/Fault/ExceptionUsuarioNoEncontrado")
    })
    public boolean hayPostulacionW(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws ExceptionUsuarioNoEncontrado_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @param arg7
     * @return
     *     returns boolean
     * @throws ErrorAgregarUsuario_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.logica/Servidor/altaEmpresaURLyImagenRequest", output = "http://servidor.logica/Servidor/altaEmpresaURLyImagenResponse", fault = {
        @FaultAction(className = ErrorAgregarUsuario_Exception.class, value = "http://servidor.logica/Servidor/altaEmpresaURLyImagen/Fault/ErrorAgregarUsuario")
    })
    public boolean altaEmpresaURLyImagen(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5,
        @WebParam(name = "arg6", partName = "arg6")
        String arg6,
        @WebParam(name = "arg7", partName = "arg7")
        byte[] arg7)
        throws ErrorAgregarUsuario_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @param arg7
     * @return
     *     returns boolean
     * @throws ErrorAgregarUsuario_Exception
     * @throws ExceptionFechaInvalida_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.logica/Servidor/altaPostulanteImagenRequest", output = "http://servidor.logica/Servidor/altaPostulanteImagenResponse", fault = {
        @FaultAction(className = ExceptionFechaInvalida_Exception.class, value = "http://servidor.logica/Servidor/altaPostulanteImagen/Fault/ExceptionFechaInvalida"),
        @FaultAction(className = ErrorAgregarUsuario_Exception.class, value = "http://servidor.logica/Servidor/altaPostulanteImagen/Fault/ErrorAgregarUsuario")
    })
    public boolean altaPostulanteImagen(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5,
        @WebParam(name = "arg6", partName = "arg6")
        String arg6,
        @WebParam(name = "arg7", partName = "arg7")
        byte[] arg7)
        throws ErrorAgregarUsuario_Exception, ExceptionFechaInvalida_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @return
     *     returns boolean
     * @throws ErrorAgregarUsuario_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.logica/Servidor/altaEmpresaImagenRequest", output = "http://servidor.logica/Servidor/altaEmpresaImagenResponse", fault = {
        @FaultAction(className = ErrorAgregarUsuario_Exception.class, value = "http://servidor.logica/Servidor/altaEmpresaImagen/Fault/ErrorAgregarUsuario")
    })
    public boolean altaEmpresaImagen(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5,
        @WebParam(name = "arg6", partName = "arg6")
        byte[] arg6)
        throws ErrorAgregarUsuario_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @return
     *     returns boolean
     * @throws ExceptionUsuarioNoEncontrado_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.logica/Servidor/modificarPostulacionRequest", output = "http://servidor.logica/Servidor/modificarPostulacionResponse", fault = {
        @FaultAction(className = ExceptionUsuarioNoEncontrado_Exception.class, value = "http://servidor.logica/Servidor/modificarPostulacion/Fault/ExceptionUsuarioNoEncontrado")
    })
    public boolean modificarPostulacion(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3)
        throws ExceptionUsuarioNoEncontrado_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns logica.servidor.WrapperLista
     * @throws ExceptionUsuarioNoEncontrado_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.logica/Servidor/listarPostulacionesPostulanteRequest", output = "http://servidor.logica/Servidor/listarPostulacionesPostulanteResponse", fault = {
        @FaultAction(className = ExceptionUsuarioNoEncontrado_Exception.class, value = "http://servidor.logica/Servidor/listarPostulacionesPostulante/Fault/ExceptionUsuarioNoEncontrado")
    })
    public WrapperLista listarPostulacionesPostulante(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws ExceptionUsuarioNoEncontrado_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.logica/Servidor/existeUsuarioConNicknameRequest", output = "http://servidor.logica/Servidor/existeUsuarioConNicknameResponse")
    public boolean existeUsuarioConNickname(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.logica/Servidor/existeUsuarioConEmailRequest", output = "http://servidor.logica/Servidor/existeUsuarioConEmailResponse")
    public boolean existeUsuarioConEmail(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @throws ExceptionUsuarioNoEncontrado_Exception
     * @throws ExceptionUsuarioSeSigueASiMismo_Exception
     */
    @WebMethod
    @Action(input = "http://servidor.logica/Servidor/seguirUsuarioRequest", output = "http://servidor.logica/Servidor/seguirUsuarioResponse", fault = {
        @FaultAction(className = ExceptionUsuarioSeSigueASiMismo_Exception.class, value = "http://servidor.logica/Servidor/seguirUsuario/Fault/ExceptionUsuarioSeSigueASiMismo"),
        @FaultAction(className = ExceptionUsuarioNoEncontrado_Exception.class, value = "http://servidor.logica/Servidor/seguirUsuario/Fault/ExceptionUsuarioNoEncontrado")
    })
    public void seguirUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws ExceptionUsuarioNoEncontrado_Exception, ExceptionUsuarioSeSigueASiMismo_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @throws ExceptionUsuarioNoEncontrado_Exception
     * @throws ExceptionUsuarioSeSigueASiMismo_Exception
     */
    @WebMethod
    @Action(input = "http://servidor.logica/Servidor/dejarDeseguirUsuarioRequest", output = "http://servidor.logica/Servidor/dejarDeseguirUsuarioResponse", fault = {
        @FaultAction(className = ExceptionUsuarioSeSigueASiMismo_Exception.class, value = "http://servidor.logica/Servidor/dejarDeseguirUsuario/Fault/ExceptionUsuarioSeSigueASiMismo"),
        @FaultAction(className = ExceptionUsuarioNoEncontrado_Exception.class, value = "http://servidor.logica/Servidor/dejarDeseguirUsuario/Fault/ExceptionUsuarioNoEncontrado")
    })
    public void dejarDeseguirUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws ExceptionUsuarioNoEncontrado_Exception, ExceptionUsuarioSeSigueASiMismo_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns logica.servidor.WrapperLista
     * @throws ExceptionUsuarioNoEncontrado_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.logica/Servidor/obtenerSeguidoresUsuarioRequest", output = "http://servidor.logica/Servidor/obtenerSeguidoresUsuarioResponse", fault = {
        @FaultAction(className = ExceptionUsuarioNoEncontrado_Exception.class, value = "http://servidor.logica/Servidor/obtenerSeguidoresUsuario/Fault/ExceptionUsuarioNoEncontrado")
    })
    public WrapperLista obtenerSeguidoresUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws ExceptionUsuarioNoEncontrado_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns logica.servidor.WrapperLista
     * @throws ExceptionUsuarioNoEncontrado_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.logica/Servidor/obtenerSeguidosUsuarioRequest", output = "http://servidor.logica/Servidor/obtenerSeguidosUsuarioResponse", fault = {
        @FaultAction(className = ExceptionUsuarioNoEncontrado_Exception.class, value = "http://servidor.logica/Servidor/obtenerSeguidosUsuario/Fault/ExceptionUsuarioNoEncontrado")
    })
    public WrapperLista obtenerSeguidosUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws ExceptionUsuarioNoEncontrado_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns logica.servidor.DtOfertaExtendidoSinPConK
     * @throws ExceptionUsuarioNoEncontrado_Exception
     * @throws OfertaLaboralNoEncontrada_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.logica/Servidor/infoOfertaLaboralEmpresaRequest", output = "http://servidor.logica/Servidor/infoOfertaLaboralEmpresaResponse", fault = {
        @FaultAction(className = OfertaLaboralNoEncontrada_Exception.class, value = "http://servidor.logica/Servidor/infoOfertaLaboralEmpresa/Fault/OfertaLaboralNoEncontrada"),
        @FaultAction(className = ExceptionUsuarioNoEncontrado_Exception.class, value = "http://servidor.logica/Servidor/infoOfertaLaboralEmpresa/Fault/ExceptionUsuarioNoEncontrado")
    })
    public DtOfertaExtendidoSinPConK infoOfertaLaboralEmpresa(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws ExceptionUsuarioNoEncontrado_Exception, OfertaLaboralNoEncontrada_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @throws ExceptionFechaInvalida_Exception
     * @throws ExceptionUsuarioNoEncontrado_Exception
     * @throws OfertaLaboralNoEncontrada_Exception
     */
    @WebMethod
    @Action(input = "http://servidor.logica/Servidor/altaPostulacionRequest", output = "http://servidor.logica/Servidor/altaPostulacionResponse", fault = {
        @FaultAction(className = OfertaLaboralNoEncontrada_Exception.class, value = "http://servidor.logica/Servidor/altaPostulacion/Fault/OfertaLaboralNoEncontrada"),
        @FaultAction(className = ExceptionUsuarioNoEncontrado_Exception.class, value = "http://servidor.logica/Servidor/altaPostulacion/Fault/ExceptionUsuarioNoEncontrado"),
        @FaultAction(className = ExceptionFechaInvalida_Exception.class, value = "http://servidor.logica/Servidor/altaPostulacion/Fault/ExceptionFechaInvalida")
    })
    public void altaPostulacion(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5,
        @WebParam(name = "arg6", partName = "arg6")
        String arg6)
        throws ExceptionFechaInvalida_Exception, ExceptionUsuarioNoEncontrado_Exception, OfertaLaboralNoEncontrada_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns logica.servidor.WrapperLista
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.logica/Servidor/listarOfertasLaboralesKeywordsRequest", output = "http://servidor.logica/Servidor/listarOfertasLaboralesKeywordsResponse")
    public WrapperLista listarOfertasLaboralesKeywords(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns logica.servidor.WrapperLista
     * @throws ExceptionUsuarioNoEncontrado_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.logica/Servidor/listarTodasLasOfertasLaboralesRequest", output = "http://servidor.logica/Servidor/listarTodasLasOfertasLaboralesResponse", fault = {
        @FaultAction(className = ExceptionUsuarioNoEncontrado_Exception.class, value = "http://servidor.logica/Servidor/listarTodasLasOfertasLaborales/Fault/ExceptionUsuarioNoEncontrado")
    })
    public WrapperLista listarTodasLasOfertasLaborales(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws ExceptionUsuarioNoEncontrado_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns logica.servidor.DtOfertaExtendido
     * @throws OfertaLaboralNoEncontrada_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.logica/Servidor/obtenerOfertaLaboralRequest", output = "http://servidor.logica/Servidor/obtenerOfertaLaboralResponse", fault = {
        @FaultAction(className = OfertaLaboralNoEncontrada_Exception.class, value = "http://servidor.logica/Servidor/obtenerOfertaLaboral/Fault/OfertaLaboralNoEncontrada")
    })
    public DtOfertaExtendido obtenerOfertaLaboral(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws OfertaLaboralNoEncontrada_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns logica.servidor.WrapperLista
     * @throws ExceptionEmpresaInvalida_Exception
     * @throws ExceptionUsuarioNoEncontrado_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.logica/Servidor/listarPaquetesNoVencidosRequest", output = "http://servidor.logica/Servidor/listarPaquetesNoVencidosResponse", fault = {
        @FaultAction(className = ExceptionEmpresaInvalida_Exception.class, value = "http://servidor.logica/Servidor/listarPaquetesNoVencidos/Fault/ExceptionEmpresaInvalida"),
        @FaultAction(className = ExceptionUsuarioNoEncontrado_Exception.class, value = "http://servidor.logica/Servidor/listarPaquetesNoVencidos/Fault/ExceptionUsuarioNoEncontrado")
    })
    public WrapperLista listarPaquetesNoVencidos(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws ExceptionEmpresaInvalida_Exception, ExceptionUsuarioNoEncontrado_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns logica.servidor.DtTipoOferta
     * @throws ExcepcionTipoOfertaNoExistente_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.logica/Servidor/obtenerDatosTORequest", output = "http://servidor.logica/Servidor/obtenerDatosTOResponse", fault = {
        @FaultAction(className = ExcepcionTipoOfertaNoExistente_Exception.class, value = "http://servidor.logica/Servidor/obtenerDatosTO/Fault/ExcepcionTipoOfertaNoExistente")
    })
    public DtTipoOferta obtenerDatosTO(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws ExcepcionTipoOfertaNoExistente_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns logica.servidor.WrapperLista
     * @throws ExceptionUsuarioNoEncontrado_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.logica/Servidor/listarComprasPaqueteRequest", output = "http://servidor.logica/Servidor/listarComprasPaqueteResponse", fault = {
        @FaultAction(className = ExceptionUsuarioNoEncontrado_Exception.class, value = "http://servidor.logica/Servidor/listarComprasPaquete/Fault/ExceptionUsuarioNoEncontrado")
    })
    public WrapperLista listarComprasPaquete(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws ExceptionUsuarioNoEncontrado_Exception
    ;

    /**
     * 
     * @param nombreOferta
     * @param wrapperLista
     * @throws AsignarOrdenAOfertaFinalizada_Exception
     * @throws AsignarOrdenAOfertaNoVencida_Exception
     * @throws ExceptionUsuarioNoEncontrado_Exception
     * @throws OfertaLaboralNoEncontrada_Exception
     */
    @WebMethod
    @Action(input = "http://servidor.logica/Servidor/establecerPosicionesRequest", output = "http://servidor.logica/Servidor/establecerPosicionesResponse", fault = {
        @FaultAction(className = AsignarOrdenAOfertaNoVencida_Exception.class, value = "http://servidor.logica/Servidor/establecerPosiciones/Fault/AsignarOrdenAOfertaNoVencida"),
        @FaultAction(className = OfertaLaboralNoEncontrada_Exception.class, value = "http://servidor.logica/Servidor/establecerPosiciones/Fault/OfertaLaboralNoEncontrada"),
        @FaultAction(className = ExceptionUsuarioNoEncontrado_Exception.class, value = "http://servidor.logica/Servidor/establecerPosiciones/Fault/ExceptionUsuarioNoEncontrado"),
        @FaultAction(className = AsignarOrdenAOfertaFinalizada_Exception.class, value = "http://servidor.logica/Servidor/establecerPosiciones/Fault/AsignarOrdenAOfertaFinalizada")
    })
    public void establecerPosiciones(
        @WebParam(name = "nombre_oferta", partName = "nombre_oferta")
        String nombreOferta,
        @WebParam(name = "wrapperLista", partName = "wrapperLista")
        WrapperLista wrapperLista)
        throws AsignarOrdenAOfertaFinalizada_Exception, AsignarOrdenAOfertaNoVencida_Exception, ExceptionUsuarioNoEncontrado_Exception, OfertaLaboralNoEncontrada_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws OfertaLaboralNoEncontrada_Exception
     */
    @WebMethod
    @Action(input = "http://servidor.logica/Servidor/aumentarVisitaRequest", output = "http://servidor.logica/Servidor/aumentarVisitaResponse", fault = {
        @FaultAction(className = OfertaLaboralNoEncontrada_Exception.class, value = "http://servidor.logica/Servidor/aumentarVisita/Fault/OfertaLaboralNoEncontrada")
    })
    public void aumentarVisita(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws OfertaLaboralNoEncontrada_Exception
    ;

    /**
     * 
     * @param nombreOferta
     * @return
     *     returns boolean
     * @throws OfertaLaboralNoEncontrada_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.logica/Servidor/hayOrdenDefinidoRequest", output = "http://servidor.logica/Servidor/hayOrdenDefinidoResponse", fault = {
        @FaultAction(className = OfertaLaboralNoEncontrada_Exception.class, value = "http://servidor.logica/Servidor/hayOrdenDefinido/Fault/OfertaLaboralNoEncontrada")
    })
    public boolean hayOrdenDefinido(
        @WebParam(name = "nombre_oferta", partName = "nombre_oferta")
        String nombreOferta)
        throws OfertaLaboralNoEncontrada_Exception
    ;

    /**
     * 
     * @param nombreOferta
     * @throws FinalizarOfertaNoVencida_Exception
     * @throws FinalizarOfertaYaFinalizada_Exception
     * @throws OfertaLaboralNoEncontrada_Exception
     */
    @WebMethod
    @Action(input = "http://servidor.logica/Servidor/finalizarOfertaRequest", output = "http://servidor.logica/Servidor/finalizarOfertaResponse", fault = {
        @FaultAction(className = OfertaLaboralNoEncontrada_Exception.class, value = "http://servidor.logica/Servidor/finalizarOferta/Fault/OfertaLaboralNoEncontrada"),
        @FaultAction(className = FinalizarOfertaNoVencida_Exception.class, value = "http://servidor.logica/Servidor/finalizarOferta/Fault/FinalizarOfertaNoVencida"),
        @FaultAction(className = FinalizarOfertaYaFinalizada_Exception.class, value = "http://servidor.logica/Servidor/finalizarOferta/Fault/FinalizarOfertaYaFinalizada")
    })
    public void finalizarOferta(
        @WebParam(name = "nombre_oferta", partName = "nombre_oferta")
        String nombreOferta)
        throws FinalizarOfertaNoVencida_Exception, FinalizarOfertaYaFinalizada_Exception, OfertaLaboralNoEncontrada_Exception
    ;

    /**
     * 
     * @throws ErrorAgregarUsuario_Exception
     * @throws ExcepcionKeywordVacia_Exception
     * @throws ExceptionFechaInvalida_Exception
     * @throws ExceptionValidezNegativa_Exception
     */
    @WebMethod
    @Action(input = "http://servidor.logica/Servidor/cargarDatosRequest", output = "http://servidor.logica/Servidor/cargarDatosResponse", fault = {
        @FaultAction(className = ExceptionValidezNegativa_Exception.class, value = "http://servidor.logica/Servidor/cargarDatos/Fault/ExceptionValidezNegativa"),
        @FaultAction(className = ExcepcionKeywordVacia_Exception.class, value = "http://servidor.logica/Servidor/cargarDatos/Fault/ExcepcionKeywordVacia"),
        @FaultAction(className = ExceptionFechaInvalida_Exception.class, value = "http://servidor.logica/Servidor/cargarDatos/Fault/ExceptionFechaInvalida"),
        @FaultAction(className = ErrorAgregarUsuario_Exception.class, value = "http://servidor.logica/Servidor/cargarDatos/Fault/ErrorAgregarUsuario")
    })
    public void cargarDatos()
        throws ErrorAgregarUsuario_Exception, ExcepcionKeywordVacia_Exception, ExceptionFechaInvalida_Exception, ExceptionValidezNegativa_Exception
    ;

    /**
     * 
     * @return
     *     returns logica.servidor.WrapperLista
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.logica/Servidor/obtenerDTOfertasLaboralesConfirmadasRequest", output = "http://servidor.logica/Servidor/obtenerDTOfertasLaboralesConfirmadasResponse")
    public WrapperLista obtenerDTOfertasLaboralesConfirmadas();

    /**
     * 
     * @param arg0
     * @throws ExceptionUsuarioNoEncontrado_Exception
     * @throws TipoUsuarioNoValido_Exception
     */
    @WebMethod
    @Action(input = "http://servidor.logica/Servidor/modificarDatosUsuarioRequest", output = "http://servidor.logica/Servidor/modificarDatosUsuarioResponse", fault = {
        @FaultAction(className = TipoUsuarioNoValido_Exception.class, value = "http://servidor.logica/Servidor/modificarDatosUsuario/Fault/TipoUsuarioNoValido"),
        @FaultAction(className = ExceptionUsuarioNoEncontrado_Exception.class, value = "http://servidor.logica/Servidor/modificarDatosUsuario/Fault/ExceptionUsuarioNoEncontrado")
    })
    public void modificarDatosUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        DtUsuario arg0)
        throws ExceptionUsuarioNoEncontrado_Exception, TipoUsuarioNoValido_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @throws ExceptionUsuarioNoEncontrado_Exception
     * @throws OfertaLaboralNoEncontrada_Exception
     */
    @WebMethod
    @Action(input = "http://servidor.logica/Servidor/marcarFavoritoRequest", output = "http://servidor.logica/Servidor/marcarFavoritoResponse", fault = {
        @FaultAction(className = ExceptionUsuarioNoEncontrado_Exception.class, value = "http://servidor.logica/Servidor/marcarFavorito/Fault/ExceptionUsuarioNoEncontrado"),
        @FaultAction(className = OfertaLaboralNoEncontrada_Exception.class, value = "http://servidor.logica/Servidor/marcarFavorito/Fault/OfertaLaboralNoEncontrada")
    })
    public void marcarFavorito(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws ExceptionUsuarioNoEncontrado_Exception, OfertaLaboralNoEncontrada_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @throws ExceptionUsuarioNoEncontrado_Exception
     * @throws OfertaLaboralNoEncontrada_Exception
     */
    @WebMethod
    @Action(input = "http://servidor.logica/Servidor/desmarcarFavoritoRequest", output = "http://servidor.logica/Servidor/desmarcarFavoritoResponse", fault = {
        @FaultAction(className = ExceptionUsuarioNoEncontrado_Exception.class, value = "http://servidor.logica/Servidor/desmarcarFavorito/Fault/ExceptionUsuarioNoEncontrado"),
        @FaultAction(className = OfertaLaboralNoEncontrada_Exception.class, value = "http://servidor.logica/Servidor/desmarcarFavorito/Fault/OfertaLaboralNoEncontrada")
    })
    public void desmarcarFavorito(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws ExceptionUsuarioNoEncontrado_Exception, OfertaLaboralNoEncontrada_Exception
    ;

    /**
     * 
     * @param nombreOferta
     * @throws OfertaLaboralNoEncontrada_Exception
     */
    @WebMethod
    @Action(input = "http://servidor.logica/Servidor/descargarOrdenPostulantesRequest", output = "http://servidor.logica/Servidor/descargarOrdenPostulantesResponse", fault = {
        @FaultAction(className = OfertaLaboralNoEncontrada_Exception.class, value = "http://servidor.logica/Servidor/descargarOrdenPostulantes/Fault/OfertaLaboralNoEncontrada")
    })
    public void descargarOrdenPostulantes(
        @WebParam(name = "nombre_oferta", partName = "nombre_oferta")
        String nombreOferta)
        throws OfertaLaboralNoEncontrada_Exception
    ;

    /**
     * 
     * @param nombreOferta
     * @return
     *     returns logica.servidor.WrapperLista
     * @throws NoHayOrdenDefinidoDePostulantes_Exception
     * @throws OfertaLaboralNoEncontrada_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.logica/Servidor/obtenerPosicionesRequest", output = "http://servidor.logica/Servidor/obtenerPosicionesResponse", fault = {
        @FaultAction(className = OfertaLaboralNoEncontrada_Exception.class, value = "http://servidor.logica/Servidor/obtenerPosiciones/Fault/OfertaLaboralNoEncontrada"),
        @FaultAction(className = NoHayOrdenDefinidoDePostulantes_Exception.class, value = "http://servidor.logica/Servidor/obtenerPosiciones/Fault/NoHayOrdenDefinidoDePostulantes")
    })
    public WrapperLista obtenerPosiciones(
        @WebParam(name = "nombre_oferta", partName = "nombre_oferta")
        String nombreOferta)
        throws NoHayOrdenDefinidoDePostulantes_Exception, OfertaLaboralNoEncontrada_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg10
     * @param arg11
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @param arg7
     * @param arg8
     * @param arg9
     * @throws ExceptionCantidadRestanteDeUnTipoDeOfertaEnUnPaqueteEsNegativa_Exception
     * @throws ExceptionCostoPaqueteNoNegativo_Exception
     * @throws ExceptionDescuentoInvalido_Exception
     * @throws ExceptionPaqueteNoVigente_Exception
     * @throws ExceptionRemuneracionOfertaLaboralNegativa_Exception
     * @throws ExceptionUsuarioNoEncontrado_Exception
     * @throws NoExistePaquete_Exception
     */
    @WebMethod
    @Action(input = "http://servidor.logica/Servidor/altaOfertaLaboralConImagenRequest", output = "http://servidor.logica/Servidor/altaOfertaLaboralConImagenResponse", fault = {
        @FaultAction(className = ExceptionRemuneracionOfertaLaboralNegativa_Exception.class, value = "http://servidor.logica/Servidor/altaOfertaLaboralConImagen/Fault/ExceptionRemuneracionOfertaLaboralNegativa"),
        @FaultAction(className = ExceptionUsuarioNoEncontrado_Exception.class, value = "http://servidor.logica/Servidor/altaOfertaLaboralConImagen/Fault/ExceptionUsuarioNoEncontrado"),
        @FaultAction(className = NoExistePaquete_Exception.class, value = "http://servidor.logica/Servidor/altaOfertaLaboralConImagen/Fault/NoExistePaquete"),
        @FaultAction(className = ExceptionCostoPaqueteNoNegativo_Exception.class, value = "http://servidor.logica/Servidor/altaOfertaLaboralConImagen/Fault/ExceptionCostoPaqueteNoNegativo"),
        @FaultAction(className = ExceptionPaqueteNoVigente_Exception.class, value = "http://servidor.logica/Servidor/altaOfertaLaboralConImagen/Fault/ExceptionPaqueteNoVigente"),
        @FaultAction(className = ExceptionCantidadRestanteDeUnTipoDeOfertaEnUnPaqueteEsNegativa_Exception.class, value = "http://servidor.logica/Servidor/altaOfertaLaboralConImagen/Fault/ExceptionCantidadRestanteDeUnTipoDeOfertaEnUnPaqueteEsNegativa"),
        @FaultAction(className = ExceptionDescuentoInvalido_Exception.class, value = "http://servidor.logica/Servidor/altaOfertaLaboralConImagen/Fault/ExceptionDescuentoInvalido")
    })
    public void altaOfertaLaboralConImagen(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5,
        @WebParam(name = "arg6", partName = "arg6")
        float arg6,
        @WebParam(name = "arg7", partName = "arg7")
        String arg7,
        @WebParam(name = "arg8", partName = "arg8")
        String arg8,
        @WebParam(name = "arg9", partName = "arg9")
        String arg9,
        @WebParam(name = "arg10", partName = "arg10")
        byte[] arg10,
        @WebParam(name = "arg11", partName = "arg11")
        String arg11)
        throws ExceptionCantidadRestanteDeUnTipoDeOfertaEnUnPaqueteEsNegativa_Exception, ExceptionCostoPaqueteNoNegativo_Exception, ExceptionDescuentoInvalido_Exception, ExceptionPaqueteNoVigente_Exception, ExceptionRemuneracionOfertaLaboralNegativa_Exception, ExceptionUsuarioNoEncontrado_Exception, NoExistePaquete_Exception
    ;

    /**
     * 
     * @param nombreOferta
     * @return
     *     returns logica.servidor.WrapperLista
     * @throws OfertaLaboralNoEncontrada_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.logica/Servidor/listarPostulantesOfertaLaboralRequest", output = "http://servidor.logica/Servidor/listarPostulantesOfertaLaboralResponse", fault = {
        @FaultAction(className = OfertaLaboralNoEncontrada_Exception.class, value = "http://servidor.logica/Servidor/listarPostulantesOfertaLaboral/Fault/OfertaLaboralNoEncontrada")
    })
    public WrapperLista listarPostulantesOfertaLaboral(
        @WebParam(name = "nombre_oferta", partName = "nombre_oferta")
        String nombreOferta)
        throws OfertaLaboralNoEncontrada_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns java.lang.String
     * @throws ExceptionUsuarioNoEncontrado_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.logica/Servidor/obtenerFechaCompraRequest", output = "http://servidor.logica/Servidor/obtenerFechaCompraResponse", fault = {
        @FaultAction(className = ExceptionUsuarioNoEncontrado_Exception.class, value = "http://servidor.logica/Servidor/obtenerFechaCompra/Fault/ExceptionUsuarioNoEncontrado")
    })
    public String obtenerFechaCompra(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws ExceptionUsuarioNoEncontrado_Exception
    ;

    /**
     * 
     * @return
     *     returns logica.servidor.WrapperLista
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.logica/Servidor/listarEmpresasRequest", output = "http://servidor.logica/Servidor/listarEmpresasResponse")
    public WrapperLista listarEmpresas();

    /**
     * 
     * @return
     *     returns logica.servidor.WrapperLista
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.logica/Servidor/listarNicknamesUsuariosRequest", output = "http://servidor.logica/Servidor/listarNicknamesUsuariosResponse")
    public WrapperLista listarNicknamesUsuarios();

    /**
     * 
     * @return
     *     returns logica.servidor.WrapperLista
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.logica/Servidor/listarPaquetesRequest", output = "http://servidor.logica/Servidor/listarPaquetesResponse")
    public WrapperLista listarPaquetes();

    /**
     * 
     * @return
     *     returns logica.servidor.WrapperLista
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.logica/Servidor/listarKeywordsRequest", output = "http://servidor.logica/Servidor/listarKeywordsResponse")
    public WrapperLista listarKeywords();

    /**
     * 
     * @return
     *     returns logica.servidor.WrapperLista
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.logica/Servidor/listarTipoDePublicacionesRequest", output = "http://servidor.logica/Servidor/listarTipoDePublicacionesResponse")
    public WrapperLista listarTipoDePublicaciones();

    /**
     * 
     * @return
     *     returns logica.servidor.WrapperLista
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.logica/Servidor/listarOfertasLaboralesConfirmadasYNoVencidasRequest", output = "http://servidor.logica/Servidor/listarOfertasLaboralesConfirmadasYNoVencidasResponse")
    public WrapperLista listarOfertasLaboralesConfirmadasYNoVencidas();

    /**
     * 
     * @param arg0
     * @return
     *     returns logica.servidor.WrapperLista
     * @throws ExceptionUsuarioNoEncontrado_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://servidor.logica/Servidor/listarOfertasLaboralesConfirmadasRequest", output = "http://servidor.logica/Servidor/listarOfertasLaboralesConfirmadasResponse", fault = {
        @FaultAction(className = ExceptionUsuarioNoEncontrado_Exception.class, value = "http://servidor.logica/Servidor/listarOfertasLaboralesConfirmadas/Fault/ExceptionUsuarioNoEncontrado")
    })
    public WrapperLista listarOfertasLaboralesConfirmadas(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws ExceptionUsuarioNoEncontrado_Exception
    ;

}
