
package webservice;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ServidorCentral", targetNamespace = "http://webservice/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServidorCentral {


    /**
     * 
     * @return
     *     returns webservice.ListaBean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservice/ServidorCentral/listarKeywordsRequest", output = "http://webservice/ServidorCentral/listarKeywordsResponse")
    public ListaBean listarKeywords();

    /**
     * 
     * @return
     *     returns webservice.ListaBean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservice/ServidorCentral/listarNicknamesUsuariosRequest", output = "http://webservice/ServidorCentral/listarNicknamesUsuariosResponse")
    public ListaBean listarNicknamesUsuarios();

    /**
     * 
     * @return
     *     returns webservice.ListaBean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservice/ServidorCentral/listarTipoDePublicacionesRequest", output = "http://webservice/ServidorCentral/listarTipoDePublicacionesResponse")
    public ListaBean listarTipoDePublicaciones();

    /**
     * 
     * @return
     *     returns webservice.ListaBean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservice/ServidorCentral/listarPaquetesRequest", output = "http://webservice/ServidorCentral/listarPaquetesResponse")
    public ListaBean listarPaquetes();

    /**
     * 
     * @param ciu
     * @param departamento
     * @param descripcion
     * @param estadoOL
     * @param fechaA
     * @param horario
     * @param img
     * @param keys
     * @param nicknameE
     * @param nombre
     * @param paquete
     * @param remun
     * @param tipo
     * @throws ExceptionRemuneracionOfertaLaboralNegativa_Exception
     */
    @WebMethod
    @Action(input = "http://webservice/ServidorCentral/altaOfertaLaboralRequest", output = "http://webservice/ServidorCentral/altaOfertaLaboralResponse", fault = {
        @FaultAction(className = ExceptionRemuneracionOfertaLaboralNegativa_Exception.class, value = "http://webservice/ServidorCentral/altaOfertaLaboral/Fault/ExceptionRemuneracionOfertaLaboralNegativa")
    })
    public void altaOfertaLaboral(
        @WebParam(name = "nickname_e", partName = "nickname_e")
        String nicknameE,
        @WebParam(name = "tipo", partName = "tipo")
        String tipo,
        @WebParam(name = "nombre", partName = "nombre")
        String nombre,
        @WebParam(name = "descripcion", partName = "descripcion")
        String descripcion,
        @WebParam(name = "horario", partName = "horario")
        DtHorario horario,
        @WebParam(name = "remun", partName = "remun")
        float remun,
        @WebParam(name = "ciu", partName = "ciu")
        String ciu,
        @WebParam(name = "departamento", partName = "departamento")
        DepUY departamento,
        @WebParam(name = "fechaA", partName = "fechaA")
        LocalDate fechaA,
        @WebParam(name = "keys", partName = "keys")
        HashSet keys,
        @WebParam(name = "estadoOL", partName = "estadoOL")
        EstadoOL estadoOL,
        @WebParam(name = "img", partName = "img")
        byte[] img,
        @WebParam(name = "paquete", partName = "paquete")
        String paquete)
        throws ExceptionRemuneracionOfertaLaboralNegativa_Exception
    ;

    /**
     * 
     * @param nickname
     * @param paquete
     * @param valor
     * @throws ExceptionCantidadRestanteDeUnTipoDeOfertaEnUnPaqueteEsNegativa_Exception
     * @throws ExceptionCompraPaqueteConValorNegativo_Exception
     * @throws ExceptionValidezNegativa_Exception
     */
    @WebMethod
    @Action(input = "http://webservice/ServidorCentral/compraPaquetesRequest", output = "http://webservice/ServidorCentral/compraPaquetesResponse", fault = {
        @FaultAction(className = ExceptionCompraPaqueteConValorNegativo_Exception.class, value = "http://webservice/ServidorCentral/compraPaquetes/Fault/ExceptionCompraPaqueteConValorNegativo"),
        @FaultAction(className = ExceptionCantidadRestanteDeUnTipoDeOfertaEnUnPaqueteEsNegativa_Exception.class, value = "http://webservice/ServidorCentral/compraPaquetes/Fault/ExceptionCantidadRestanteDeUnTipoDeOfertaEnUnPaqueteEsNegativa"),
        @FaultAction(className = ExceptionValidezNegativa_Exception.class, value = "http://webservice/ServidorCentral/compraPaquetes/Fault/ExceptionValidezNegativa")
    })
    public void compraPaquetes(
        @WebParam(name = "nickname", partName = "nickname")
        String nickname,
        @WebParam(name = "paquete", partName = "paquete")
        String paquete,
        @WebParam(name = "valor", partName = "valor")
        int valor)
        throws ExceptionCantidadRestanteDeUnTipoDeOfertaEnUnPaqueteEsNegativa_Exception, ExceptionCompraPaqueteConValorNegativo_Exception, ExceptionValidezNegativa_Exception
    ;

    /**
     * 
     * @param apellido
     * @param contrasenia
     * @param desc
     * @param imagen
     * @param mail
     * @param nick
     * @param nombre
     * @param url
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservice/ServidorCentral/altaEmpresaURLyImagenRequest", output = "http://webservice/ServidorCentral/altaEmpresaURLyImagenResponse")
    public boolean altaEmpresaURLyImagen(
        @WebParam(name = "nick", partName = "nick")
        String nick,
        @WebParam(name = "contrasenia", partName = "contrasenia")
        String contrasenia,
        @WebParam(name = "nombre", partName = "nombre")
        String nombre,
        @WebParam(name = "apellido", partName = "apellido")
        String apellido,
        @WebParam(name = "mail", partName = "mail")
        String mail,
        @WebParam(name = "desc", partName = "desc")
        String desc,
        @WebParam(name = "URL", partName = "URL")
        String url,
        @WebParam(name = "imagen", partName = "imagen")
        byte[] imagen);

    /**
     * 
     * @param nickname
     * @return
     *     returns webservice.ListaBean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservice/ServidorCentral/listarPostulacionesPostulanteRequest", output = "http://webservice/ServidorCentral/listarPostulacionesPostulanteResponse")
    public ListaBean listarPostulacionesPostulante(
        @WebParam(name = "nickname", partName = "nickname")
        String nickname);

    /**
     * 
     * @param nickname
     * @return
     *     returns webservice.UsuarioBeanServidor
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservice/ServidorCentral/obtenerDatosUsuarioRequest", output = "http://webservice/ServidorCentral/obtenerDatosUsuarioResponse")
    public UsuarioBeanServidor obtenerDatosUsuario(
        @WebParam(name = "nickname", partName = "nickname")
        String nickname);

    /**
     * 
     * @param paquete
     * @return
     *     returns webservice.PaqueteBeanServidor
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservice/ServidorCentral/obtenerDatosPaqueteRequest", output = "http://webservice/ServidorCentral/obtenerDatosPaqueteResponse")
    public PaqueteBeanServidor obtenerDatosPaquete(
        @WebParam(name = "paquete", partName = "paquete")
        String paquete);

    /**
     * 
     * @param contrasenia
     * @param identificador
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservice/ServidorCentral/validarCredencialesRequest", output = "http://webservice/ServidorCentral/validarCredencialesResponse")
    public boolean validarCredenciales(
        @WebParam(name = "identificador", partName = "identificador")
        String identificador,
        @WebParam(name = "contrasenia", partName = "contrasenia")
        String contrasenia);

    /**
     * 
     * @param nickname
     * @return
     *     returns webservice.ListaBean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservice/ServidorCentral/listarTodasLasOfertasLaboralesRequest", output = "http://webservice/ServidorCentral/listarTodasLasOfertasLaboralesResponse")
    public ListaBean listarTodasLasOfertasLaborales(
        @WebParam(name = "nickname", partName = "nickname")
        String nickname);

    /**
     * 
     * @param nicknameParametro
     * @param nombreOferta
     * @return
     *     returns webservice.DtPostulacion
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservice/ServidorCentral/obtenerDatosPostulacionRequest", output = "http://webservice/ServidorCentral/obtenerDatosPostulacionResponse")
    public DtPostulacion obtenerDatosPostulacion(
        @WebParam(name = "nicknameParametro", partName = "nicknameParametro")
        String nicknameParametro,
        @WebParam(name = "nombreOferta", partName = "nombreOferta")
        String nombreOferta);

    /**
     * 
     * @param keyword
     * @return
     *     returns webservice.ListaBean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservice/ServidorCentral/listarOfertasLaboralesKeywordsRequest", output = "http://webservice/ServidorCentral/listarOfertasLaboralesKeywordsResponse")
    public ListaBean listarOfertasLaboralesKeywords(
        @WebParam(name = "keyword", partName = "keyword")
        String keyword);

    /**
     * 
     * @return
     *     returns webservice.ListaBean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservice/ServidorCentral/listarTodasLasOfertasLaboralesConfirmadasRequest", output = "http://webservice/ServidorCentral/listarTodasLasOfertasLaboralesConfirmadasResponse")
    public ListaBean listarTodasLasOfertasLaboralesConfirmadas();

    /**
     * 
     * @param consulta
     * @return
     *     returns webservice.ListaBean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservice/ServidorCentral/listarOfertasLaboralesConfirmadasConsultaRequest", output = "http://webservice/ServidorCentral/listarOfertasLaboralesConfirmadasConsultaResponse")
    public ListaBean listarOfertasLaboralesConfirmadasConsulta(
        @WebParam(name = "consulta", partName = "consulta")
        String consulta);

    /**
     * 
     * @param empresaNickname
     * @param nombreOferta
     * @return
     *     returns webservice.DtOfertaExtendidoSinPConK
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservice/ServidorCentral/obtenerInformacionOfertaLaboralEmpresaRequest", output = "http://webservice/ServidorCentral/obtenerInformacionOfertaLaboralEmpresaResponse")
    public DtOfertaExtendidoSinPConK obtenerInformacionOfertaLaboralEmpresa(
        @WebParam(name = "empresaNickname", partName = "empresaNickname")
        String empresaNickname,
        @WebParam(name = "nombreOferta", partName = "nombreOferta")
        String nombreOferta);

    /**
     * 
     * @param nombreOferta
     * @param postulanteNickname
     * @return
     *     returns webservice.DtOfertaExtendidoSinPConK
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservice/ServidorCentral/obtenerInformacionOfertaLaboralPostulanteRequest", output = "http://webservice/ServidorCentral/obtenerInformacionOfertaLaboralPostulanteResponse")
    public DtOfertaExtendidoSinPConK obtenerInformacionOfertaLaboralPostulante(
        @WebParam(name = "postulanteNickname", partName = "postulanteNickname")
        String postulanteNickname,
        @WebParam(name = "nombreOferta", partName = "nombreOferta")
        String nombreOferta);

    /**
     * 
     * @param nombreOferta
     * @return
     *     returns webservice.DtOfertaExtendidoSinPConK
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservice/ServidorCentral/obtenerInformacionOfertaLaboralVisitanteRequest", output = "http://webservice/ServidorCentral/obtenerInformacionOfertaLaboralVisitanteResponse")
    public DtOfertaExtendidoSinPConK obtenerInformacionOfertaLaboralVisitante(
        @WebParam(name = "nombreOferta", partName = "nombreOferta")
        String nombreOferta);

    /**
     * 
     * @param nickname
     * @return
     *     returns webservice.ListaBean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservice/ServidorCentral/listarPaquetesDeEmpresaRequest", output = "http://webservice/ServidorCentral/listarPaquetesDeEmpresaResponse")
    public ListaBean listarPaquetesDeEmpresa(
        @WebParam(name = "nickname", partName = "nickname")
        String nickname);

    /**
     * 
     * @param nickname
     * @return
     *     returns webservice.ListaBean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservice/ServidorCentral/listarOfertasConfirmadasDeEmpresaRequest", output = "http://webservice/ServidorCentral/listarOfertasConfirmadasDeEmpresaResponse")
    public ListaBean listarOfertasConfirmadasDeEmpresa(
        @WebParam(name = "nickname", partName = "nickname")
        String nickname);

    /**
     * 
     * @param nombreOferta
     * @return
     *     returns webservice.DtOfertaExtendido
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservice/ServidorCentral/obtenerOfertaLaboralExtendidaRequest", output = "http://webservice/ServidorCentral/obtenerOfertaLaboralExtendidaResponse")
    public DtOfertaExtendido obtenerOfertaLaboralExtendida(
        @WebParam(name = "nombreOferta", partName = "nombreOferta")
        String nombreOferta);

    /**
     * 
     * @param arg0
     * @return
     *     returns webservice.OfertaLaboralBeanServidor
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservice/ServidorCentral/obtenerDatosOfertaLaboralRequest", output = "http://webservice/ServidorCentral/obtenerDatosOfertaLaboralResponse")
    public OfertaLaboralBeanServidor obtenerDatosOfertaLaboral(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
